configs/config.testnet.yaml, periodic/src/price_source/chainlink.rs, periodic/src/price_source/coingecko.rs, primitives/src/cli.rs, primitives/src/eth.rs, relayer/src/service.rs
- Support DAI as a oracle price asset on testnet
=> CCCP-210, feature: support dai price oracle on testnet

.gitignore, client/src/eth/blocks.rs, client/src/eth/mod.rs, client/src/eth/tx/eip1559_manager.rs, client/src/eth/tx/legacy_manager.rs, configs/config.mainnet.yaml, configs/config.testnet.yaml, periodic/src/price_feeder.rs, primitives/src/errors.rs, sonar-project.properties
- on start 과정 개선
- 불필요한 RPC 콜 제거
- config에 명시된 체인 아이디와 provider의 실제 체인 아이디 비교 검증
- BFC 밸런스 체크 (시작시 최소 1 BFC 이상)
- 기타
- 패닉 메시지 통일
- secondary price source 실패 시, DAI에 대한 디폴트 가격 추가
- config에 Base의 is_relay_target을 false로 설정
- 제거가 안된 sonar 관련 파일 제거
=> CCCP-228, feature: enhance bootstrap verifications

client/src/eth/blocks.rs, client/src/eth/mod.rs, client/src/eth/tx/eip1559_manager.rs, client/src/eth/tx/legacy_manager.rs, client/src/eth/tx/mod.rs, primitives/src/errors.rs
- 트랜잭션 전송 이전에 현재 남은 밸런스와 예상 수수료를 비교하여 수행이 가능한지 검증
=> CCCP-229, feature: balance check before sending transactions

Cargo.toml, client/src/eth/tx/legacy_manager.rs, primitives/src/cli.rs, relayer/Cargo.toml, relayer/src/service.rs, rust-toolchain
- Set relayer version to `v1.0.4`
- Set to stable Rust
- Update Substrate branches to `bifrost-polkadot-v0.9.43`
=> CCCP-232, deploy: release v1.0.4

client/src/eth/mod.rs
=> CCCP-264, fix: resolve invalid bootstrap offset height

relayer/Cargo.toml
=> CCCP-265, deploy: release v1.0.5

client/src/eth/events.rs, client/src/eth/handlers/execution_filter.rs, client/src/eth/handlers/socket_relay_handler.rs, client/src/eth/tx/eip1559_manager.rs, client/src/eth/tx/legacy_manager.rs, periodic/src/socket_rollback_handler.rs, primitives/src/periodic.rs
- `TransactionManager`에서 gas estimation 단계 이전에 트랜잭션(`tx_request`)의 gas price 파라미터들 설정
- Socket 메시지의 디폴트 variants를 `0x00`이 아닌 `0x`로 간주하도록 변경
- `SocketRollbackHandler`에서 `SocketRelayBuilder::get_sorted_signatures()` 안에서 호출되는 `get_client()` 메소드를 항상 Bifrost의 `EthClient`를 반환할 수 있도록 변경
- `ROLLBACK_CHECK_MINIMUM_INTERVAL`를 5분에서 3분으로 단축
=> fix: resolve feature issues

configs/config.testnet.yaml, relayer/src/main.rs
- Support Sepolia-based chains
- eth-sepolia
- base-sepolia
- arbitrum-sepolia
⚠️ Goerli configurations will be permanently removed when publicly deprecated
=> CCCP-294, feature: support sepolia

configs/config.testnet.yaml
- Remove the following Goerli-based chains
- Goerli
- Base Goerli
- Arbitrum Goerli
=> Discontinue Goerli-based chains support

client/src/eth/handlers/socket_relay_handler.rs, configs/config.testnet.yaml, relayer/src/main.rs
=> CCCP-306, fix: socket variants issue

client/src/eth/handlers/socket_relay_handler.rs
=> CCCP-306-2, fix: socket variants comparison method

client/src/eth/events.rs, client/src/eth/tx/eip1559_manager.rs, client/src/eth/tx/legacy_manager.rs, client/src/eth/tx/task.rs, primitives/src/cli.rs, relayer/src/service.rs, relayer/src/verification.rs
Replace GasEscalatorMiddleware with stalled tx handler .
=> CCCP-304, Replace GasEscalatorMiddleware with stalled tx handler

client/Cargo.toml, client/src/eth/handlers/mod.rs, client/src/eth/handlers/socket_relay_handler.rs
* Implement 'v2' feature flag for conditional compilation
=> CCCP-322, 'v2' conditional compilation

configs/config.mainnet.yaml, configs/config.testnet.yaml, relayer/Cargo.toml, rust-toolchain
- update config yaml
- remove vault address
- replace handler type `BridgeRelay` to `Socket`
- increase relayer version to v1.1.0
- use stable rust
=> CCCP-321, deps: release v1.1.0

client/src/eth/handlers/socket_relay_handler.rs
=> fix: add missing feature on test code

abi/abi.registration_pool.bifrost.json, abi/abi.relay_executive.bifrost.json, abi/abi.socket_queue.bifrost.json, configs/config.mainnet.yaml, configs/config.testnet.yaml, primitives/src/cli.rs, primitives/src/contracts/mod.rs, primitives/src/contracts/registration_pool.rs, primitives/src/contracts/relay_executive.rs, primitives/src/contracts/socket_queue.rs, primitives/src/eth.rs, relayer/src/service.rs
- precompile contract instance 추가
=> CCCP-360, feature: add precompile contract instances

abi/abi.registration_pool.bifrost.json, abi/abi.socket_queue.bifrost.json
- Precompile ABI update
- precompile_btc_registration_pool
- user_address()
- precompile_btc_socket_queue
- outbound_tx()
=> chore: update precompile abi

configs/config.testnet.yaml
=> CCCP-370, deps: deprecate mumbai chain

client/src/btc/block.rs, client/src/btc/handlers/inbound.rs, client/src/btc/handlers/mod.rs, client/src/btc/handlers/outbound.rs, client/src/btc/mod.rs, client/src/btc/storage/keypair.rs, client/src/btc/storage/pending_outbound.rs, client/src/substrate/traits.rs, client/src/substrate/tx/unsigned_manager.rs, configs/config.mainnet.yaml, configs/config.testnet.yaml, periodic/src/pub_key_submitter.rs, primitives/src/cli.rs, primitives/src/constants/cli.rs, primitives/src/constants/errors.rs, primitives/src/eth.rs, primitives/src/tx.rs, relayer/src/service.rs
- Check Bifrost-only protocol contract existance (at on-start)
- Remove unwrap() and unused todo!() / panic!()
- Implement BtcClient (for rpc call retries on-failure)
- Add some logs
- Add docstrings
- Apply cargo-clipppy
=> CCCP-367, chore: cleanup code

client/src/eth/tx/eip1559_manager.rs, client/src/eth/tx/legacy_manager.rs, primitives/src/tx.rs
*  if gas already set, do not estimate gas
=> fix: gas estimation

client/src/btc/block.rs, client/src/btc/handlers/inbound.rs, client/src/btc/handlers/mod.rs, client/src/btc/handlers/outbound.rs, client/src/btc/storage/keypair.rs, client/src/eth/events.rs, client/src/eth/handlers/roundup_relay_handler.rs, client/src/eth/handlers/socket_relay_handler.rs, client/src/eth/mod.rs, client/src/eth/traits.rs, periodic/src/heartbeat_sender.rs, periodic/src/pub_key_submitter.rs, periodic/src/roundup_emitter.rs, primitives/src/bootstrap.rs, primitives/src/constants/config.rs, relayer/src/service.rs
- Bitcoin inbound/outbound bootstrap
- 각 핸들러가 아닌 BlockManager에서 한번에 진행
- [참고] Bitcoin의 평균 블록 시간은 고정 상수로 10분으로 설정
=> CCCP-371, feature: bitcoin inbound & outbound bootstrap

.gitignore, client/Cargo.toml, client/src/btc/block.rs, client/src/btc/handlers/mod.rs, client/src/btc/handlers/psbt_signer.rs, client/src/btc/storage/keypair.rs, client/src/substrate/tx/unsigned_manager.rs, periodic/Cargo.toml, periodic/src/pub_key_submitter.rs, periodic/src/socket_rollback_emitter.rs, primitives/src/cli.rs, primitives/src/constants/cli.rs, primitives/src/constants/config.rs, primitives/src/substrate.rs, primitives/src/tx.rs, relayer/src/service.rs
- PubKeySubmitter (정상 제출 테스트 완료)
- 서명 생성 올바르게 수정
- 빠진 submit_system_vault_key() 관련 로직 추가
- PsbtSigner (testbed에서 테스트 필요)
- 서명 생성 올바르게 수정
- UnsignedTransactionManager
- retry 전부 소모시 return 조건문 추가
- KeypairStorage
- insert() 및 get() 함수에서 사용된 blocking_*() 함수들 사용시, panic이 발생하는 문제로 blocking이 없는 함수들로 대체
- SocketRollbackHandler
- Bitcoin rollback 방지
- https://github.com/bifrost-platform/bifrost-node/pull/41/commits/035af73aaa2c9127887637f74cb2ad1ab024bb32
=> minor fixes

client/src/btc/block.rs, client/src/btc/handlers/inbound.rs, client/src/btc/handlers/outbound.rs, client/src/eth/handlers/socket_relay_handler.rs, client/src/eth/mod.rs, periodic/src/socket_rollback_emitter.rs, primitives/src/eth.rs, relayer/src/service.rs
- BTC Inbound는 마지막 단계를 Accepted/Reverted로 간주하도록 설정
- BitcoinSocket::poll() 함수 호출 이전에, 릴레이어가 투표했는지 검사
=> Alex/minor fixes (2)

primitives/src/bootstrap.rs
- Use correct socket barrier length on bootstrap enabled/disabled
=> CCCP-390, fix: bitcoin bootstrap stuck

client/src/btc/block.rs, configs/config.mainnet.yaml, configs/config.testnet.yaml, primitives/src/cli.rs, relayer/src/service.rs
- Move btc block offset from `btc_provider` to `bootstrap_config`
=> Bootstrap config minor update

Cargo.toml, primitives/src/tx.rs
- 네이밍 업데이트
- Payload -> DefaultPayload
- TxPayload -> Payload
=> deps: update subxt version

Cargo.toml, relayer/src/service.rs
- Set `BitcoinClient`'s request timeout (=60 sec)
- Update `polkadot-sdk`'s branch to `bifrost-polkadot-v1.12.0`
- due to build issues on the previous version
=> Feature: add btc client request timeout

client/src/btc/handlers/inbound.rs
bitcoin txid from bifrost network is in little endian, convert it to big endian.
=> fix: endian issue

periodic/src/bitcoin_rollback_verifier.rs
- Add 6 block confirmations check
=> CCCP-423, fix: add block confirmations check

client/src/eth/handlers/socket_relay_handler.rs
- BRP 롤백의 최종 단계는 `Accepted`만 가능하므로, `Reverted` 상태 체크 부분 제거
=> CCCP-424, fix: remove unreachable state check

client/src/btc/block.rs, primitives/src/cli.rs, primitives/src/constants/cli.rs, relayer/src/service.rs
- Add bitcoin block confirmations option and remove hard-coded code
=> CCCP-425, fix: add bitcoin block confirmations option

client/src/btc/block.rs, client/src/btc/handlers/inbound.rs, client/src/btc/handlers/mod.rs, client/src/btc/handlers/outbound.rs, client/src/eth/events.rs, client/src/eth/handlers/roundup_relay_handler.rs, client/src/eth/handlers/socket_relay_handler.rs, client/src/eth/mod.rs, client/src/eth/traits.rs, client/src/eth/tx/eip1559_manager.rs, client/src/eth/tx/legacy_manager.rs, client/src/substrate/traits.rs, client/src/substrate/tx/extrinsic_manager.rs, periodic/src/bitcoin_rollback_verifier.rs, periodic/src/heartbeat_sender.rs, periodic/src/keypair_migrator.rs, periodic/src/price_feeder.rs, periodic/src/price_source/chainlink.rs, periodic/src/price_source/mod.rs, periodic/src/price_source/upbit.rs, periodic/src/psbt_signer.rs, periodic/src/pub_key_presubmitter.rs, periodic/src/pub_key_submitter.rs, periodic/src/roundup_emitter.rs, periodic/src/socket_rollback_emitter.rs, relayer/src/service.rs
=> chore: generic subxt signer

periodic/src/bitcoin_rollback_verifier.rs
=> CCCP-427, fix: add missing signature domain

primitives/src/constants/cli.rs
- use a more safe confirmation as default
=> CCCP-449, fix: use a more safe confirmation as default

client/src/btc/storage/pending_outbound.rs, periodic/src/bitcoin_rollback_verifier.rs
* https://github.com/bifrost-platform/bifrost-node/pull/86
=> NODE-141, chore: include field `is_approved` into signature message

client/src/btc/block.rs
=> fix: use correct `to_block`

.gitignore, client/src/substrate/traits.rs
* Mute sentry on BtcSocketQueue::RequestDNE
=> Mute sentry on BtcSocketQueue::RequestDNE

relayer/Cargo.toml
=> release v2.0.1

client/src/substrate/tx/unsigned_manager.rs
=> fix: update OnlineClient init

primitives/src/bootstrap.rs
=> fix: use correct roundup barrier count

periodic/src/keypair_migrator.rs, periodic/src/pub_key_presubmitter.rs
=> fix: apply unhandled OnlineClient init

README.md
=> docs: update readme (add bitcoin)

Cargo.toml, client/src/eth/mod.rs, configs/config.mainnet.yaml, configs/config.testnet.yaml, primitives/src/cli.rs, primitives/src/constants/errors.rs, relayer/Cargo.toml, relayer/src/main.rs, relayer/src/service.rs
* now can use `AwsSigner` | `LocalSigner`
=> CCCP-475 integrate aws-kms

README.md, configs/config.mainnet.yaml
- Support Oasys mainnet
- [Homepage](https://www.oasys.games/)
- [Explorer](https://explorer.oasys.games/)
- Recommended RPC provider
- [BlockPi](https://blockpi.io/chain/oasys)
- Create an account and use your private endpoint for full usage
=> CCCP-499, feat: support Oasys mainnet

client/src/eth/events.rs, client/src/eth/handlers/roundup_relay_handler.rs, client/src/eth/mod.rs, periodic/src/roundup_emitter.rs
=> relay as previous selected
